- name: Disable redis default
  ansible.builtin.shell: dnf module disable redis -y

- name: Enable redis 7
  ansible.builtin.shell: dnf module enable redis:7

- name: Install Redis 7
  ansible.builtin.dnf:
    name: redis
    state: latest

- name: Redis Config file - Update Listen Address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Redis Config file - Update Protected Mode
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: 'protected-mode no'

- name: Start and Enable Redis Service
  ansible.builtin.systemd_Service:
    name: redis
    state: restarted
    enabled: true
