component: frontend
app_path: /usr/share/nginx/html

secrets: "{{ lookup('hashi_vault', 'secret=roboshop-{{ env }}/data/frontend token={{vault_token}} url=https://vault-internal.shefalidevops.shop:8200 validate_certs=false')}}"
