- name: Copy rabbitmq repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server

- name: Start Rabbitmq Service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted
    enabled: true

- name: add user and set permission
  ansible.builtin.shell: rabbitmqctl add_user {{ secrets.AMQP_USER }} {{ secrets.AMQP_PASS }} ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

