component: payment
app_path: /app

secrets: "{{ lookup('hashi_vault', 'secret=roboshop-{{ env }}/data/payment token={{vault_token}} url=https://vault-internal.shefalidevops.shop:8200 validate_certs=false')}}"
