- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server

- name: Start and Enable MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Setup MySQL Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ secrets.MYSQL_ROOT_PASSWORD }}