- name: Load MongoDB Schema
  when: schema_Setup == "mongo"
  block:
    - name: COpy MongoDB repo file
      ansible.builtin.template:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB Client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: latest

    - name: Load Master Data
      ansible.builtin.shell: mongosh --host 172.31.89.237 </app/db/master-data.js
